<?php
/** Runtime-free assertions for first-save event slug repair. */
declare(strict_types=1);
class WP_Post { public $ID; public $post_status; public $post_title; public function __construct($id,$status,$title){$this->ID=$id;$this->post_status=$status;$this->post_title=$title;} }
$GLOBALS['slug_posts']=array();$GLOBALS['slug_locale']='en';$GLOBALS['slug_existing']=array();$GLOBALS['slug_unique_calls']=0;$GLOBALS['slug_cases']=0;
function wp_strip_all_tags($v){return strip_tags((string)$v);} function absint($v){return abs((int)$v);} function get_post($id){return $GLOBALS['slug_posts'][absint($id)]??null;}
function __($text){return 'Auto Draft'===$text&&'fr'===$GLOBALS['slug_locale']?'Brouillon auto':$text;}
function sanitize_title($v){$v=strtr((string)$v,array('É'=>'E','é'=>'e','È'=>'E','è'=>'e','Ê'=>'E','ê'=>'e','À'=>'A','à'=>'a','Ù'=>'U','ù'=>'u','Ô'=>'O','ô'=>'o'));return trim((string)preg_replace('/[^a-z0-9]+/','-',strtolower($v)),'-');}
function wp_unique_post_slug($slug,...$unused){$GLOBALS['slug_unique_calls']++;if(!in_array($slug,$GLOBALS['slug_existing'],true)){return $slug;}$n=2;while(in_array($slug.'-'.$n,$GLOBALS['slug_existing'],true)){$n++;}return $slug.'-'.$n;}
$source=file_get_contents(dirname(__DIR__).'/wp-seed-events.php');$start=strpos($source,'function wp_seed_events_prepare_event_title_and_slug');$end=strpos($source,'function wp_seed_events_title_required_redirect',$start);if(false===$source||false===$start||false===$end){throw new RuntimeException('Unable to load slug functions.');}eval(substr($source,$start,$end-$start));
function slug_assert($c,$m){if(!$c){throw new RuntimeException($m);}} function slug_case($l,$cb){$GLOBALS['slug_cases']++;$GLOBALS['slug_existing']=array();$GLOBALS['slug_unique_calls']=0;$GLOBALS['wp_seed_events_title_required_notice']=false;$cb();echo '[OK] '.$GLOBALS['slug_cases'].' '.$l.PHP_EOL;}
function slug_post($id,$status='auto-draft',$title='Auto Draft'){$GLOBALS['slug_posts'][$id]=new WP_Post($id,$status,$title);} function slug_prepare($id,$title,$slug,$status='draft',$type='wp_seed_event'){return wp_seed_events_prepare_event_title_and_slug(array('post_type'=>$type,'post_status'=>$status,'post_title'=>$title,'post_name'=>$slug),array('ID'=>$id));}
slug_case('auto-draft',function(){$GLOBALS['slug_locale']='en';slug_post(1);slug_assert('event-one'===slug_prepare(1,'Event One','auto-draft')['post_name'],'not repaired');});
slug_case('auto-draft-2',function(){$GLOBALS['slug_locale']='en';slug_post(2);slug_assert('event-two'===slug_prepare(2,'Event Two','auto-draft-2')['post_name'],'suffix not repaired');});
slug_case('brouillon-auto',function(){$GLOBALS['slug_locale']='fr';slug_post(3,'auto-draft','Brouillon auto');slug_assert('danse-libre-2026'===slug_prepare(3,'Danse libre 2026','brouillon-auto')['post_name'],'French slug not repaired');});
slug_case('brouillon-auto-2',function(){$GLOBALS['slug_locale']='fr';slug_post(4,'auto-draft','Brouillon auto');slug_assert('danse-libre-2026'===slug_prepare(4,'Danse libre 2026','brouillon-auto-2')['post_name'],'French suffix not repaired');});
slug_case('brouillon-auto-25',function(){$GLOBALS['slug_locale']='fr';slug_post(5,'auto-draft','Brouillon auto');slug_assert('danse-libre-2026'===slug_prepare(5,'Danse libre 2026','brouillon-auto-25')['post_name'],'large suffix not repaired');});
slug_case('accented title',function(){$GLOBALS['slug_locale']='fr';slug_post(6,'auto-draft','Brouillon auto');slug_assert('evenement-d-ete'===slug_prepare(6,'Événement d’été','brouillon-auto-3')['post_name'],'accented title differs');});
slug_case('apostrophe title',function(){$GLOBALS['slug_locale']='fr';slug_post(7,'auto-draft','Brouillon auto');slug_assert('l-atelier-d-emilie'===slug_prepare(7,'L’atelier d’Émilie','brouillon-auto-4')['post_name'],'apostrophe title differs');});
slug_case('empty title',function(){$GLOBALS['slug_locale']='fr';slug_post(8,'auto-draft','Brouillon auto');$d=slug_prepare(8,'','brouillon-auto-5');slug_assert('brouillon-auto-5'===$d['post_name']&&0===$GLOBALS['slug_unique_calls'],'empty title changed slug');});
slug_case('empty published title',function(){$GLOBALS['slug_locale']='fr';slug_post(9,'auto-draft','Brouillon auto');$d=slug_prepare(9,'','brouillon-auto-5','publish');slug_assert('draft'===$d['post_status']&&'brouillon-auto-5'===$d['post_name'],'publish guard differs');});
slug_case('manual slug',function(){$GLOBALS['slug_locale']='fr';slug_post(10,'auto-draft','Brouillon auto');slug_assert('mon-url-personnalisee'===slug_prepare(10,'Danse libre 2026','mon-url-personnalisee')['post_name'],'manual slug changed');});
slug_case('partial resemblance',function(){$GLOBALS['slug_locale']='fr';slug_post(11,'auto-draft','Brouillon auto');slug_assert('archives-brouillon-auto'===slug_prepare(11,'Archives','archives-brouillon-auto')['post_name'],'partial match changed');});
slug_case('published unchanged',function(){$GLOBALS['slug_locale']='fr';slug_post(12,'publish','Danse libre 2025-2026');slug_assert('brouillon-auto-4'===slug_prepare(12,'Danse libre 2025-2026','brouillon-auto-4','publish')['post_name'],'published URL migrated');});
slug_case('later draft unchanged',function(){$GLOBALS['slug_locale']='fr';slug_post(13,'auto-draft','Brouillon auto');$first=slug_prepare(13,'Danse libre 2026','brouillon-auto-2');$GLOBALS['slug_posts'][13]->post_status='draft';$second=slug_prepare(13,'Nouveau titre',$first['post_name']);slug_assert('danse-libre-2026'===$second['post_name']&&1===$GLOBALS['slug_unique_calls'],'later save rewrote slug');});
slug_case('WordPress uniqueness',function(){$GLOBALS['slug_locale']='fr';$GLOBALS['slug_existing']=array('danse-libre-2026','danse-libre-2026-2');slug_post(14,'auto-draft','Brouillon auto');slug_assert('danse-libre-2026-3'===slug_prepare(14,'Danse libre 2026','brouillon-auto-2')['post_name'],'unique suffix differs');});
slug_case('other locale stored title',function(){$GLOBALS['slug_locale']='en';slug_post(15,'auto-draft','Entwurf automatisch');slug_assert('neues-ereignis'===slug_prepare(15,'Neues Ereignis','entwurf-automatisch-2')['post_name'],'stored locale not recognized');});
slug_case('no recursive save',function()use($source){$s=substr($source,strpos($source,'function wp_seed_events_prepare_event_title_and_slug'),strpos($source,'function wp_seed_events_title_required_redirect')-strpos($source,'function wp_seed_events_prepare_event_title_and_slug'));slug_assert(false===strpos($s,'wp_update_post')&&false===strpos($s,'wp_insert_post'),'recursive write introduced');});
slug_case('other post type',function(){$d=slug_prepare(16,'Regular Page','auto-draft-2','draft','page');slug_assert('auto-draft-2'===$d['post_name']&&0===$GLOBALS['slug_unique_calls'],'other post type changed');});
echo '[OK] '.$GLOBALS['slug_cases'].'/'.$GLOBALS['slug_cases'].' event slug cases passed.'.PHP_EOL;
