const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const pluginRoot = path.resolve(root, '..', '..', '..', '..');
const read = (...parts) => fs.readFileSync(path.join(...parts), 'utf8');
const metadata = JSON.parse(read(root, 'src/block.json'));
const built = JSON.parse(read(root, 'build/block.json'));
const source = read(root, 'src/index.js');
const php = read(pluginRoot, 'includes/integrations/gutenberg/event-visuals-block.php');
const preview = read(pluginRoot, 'includes/integrations/gutenberg/event-visuals-preview.php');
let passed = 0;
const test = (name, fn) => { fn(); passed += 1; console.log(`OK ${passed} - ${name}`); };
test('block identity is stable', () => assert.strictEqual(metadata.name, 'wp-seed-events/event-visuals-block'));
test('Block API v3 dynamic block', () => { assert.strictEqual(metadata.apiVersion, 3); assert.ok(source.includes('save: () => null')); });
test('built metadata matches source', () => assert.deepStrictEqual(built, metadata));
test('legacy document storage remains readable but UI is image-only', () => { assert.ok(Object.hasOwn(metadata.attributes, 'show_document')); assert.ok(!source.includes('Afficher le document')); });
test('one click action has exact values', () => assert.deepStrictEqual(metadata.attributes.click_action.enum, ['none', 'lightbox', 'original']));
test('layouts have exact values', () => assert.deepStrictEqual(metadata.attributes.layout.enum, ['vertical', 'horizontal', 'grid']));
test('new instances default to no click', () => assert.strictEqual(metadata.attributes.click_action.default, 'none'));
test('responsive grid columns exist', () => ['columns', 'columns_tablet', 'columns_phone'].forEach((key) => assert.ok(Object.hasOwn(metadata.attributes, key))));
test('collection controls exist', () => ['horizontal_gap', 'vertical_gap', 'align_items', 'justify_content', 'wrap'].forEach((key) => assert.ok(Object.hasOwn(metadata.attributes, key))));
test('context is card-local', () => assert.deepStrictEqual(metadata.usesContext, ['postId', 'postType', 'queryId']));
test('Event Data and renderer are used once', () => { assert.strictEqual((php.match(/wp_seed_events_get_event_data\s*\(/g) || []).length, 1); assert.strictEqual((php.match(/wp_seed_events_render_public_event_visuals_section\s*\(/g) || []).length, 1); });
test('no direct meta SQL or shortcode', () => [php, preview, source].forEach((text) => { assert.ok(!text.includes('get_post_meta')); assert.ok(!text.includes('$wpdb')); assert.ok(!text.includes('do_shortcode')); }));
test('preview is protected and abortable', () => { assert.ok(preview.includes('current_user_can')); assert.ok(source.includes('AbortController')); assert.ok(source.includes('requestSequence')); });
test('frontend uses native block supports', () => { assert.ok(php.includes('get_block_wrapper_attributes')); assert.strictEqual(metadata.supports.html, false); });
test('compiled assets are non-empty', () => { assert.ok(fs.statSync(path.join(root, 'build/index.js')).size > 0); assert.ok(fs.statSync(path.join(root, 'build/index.asset.php')).size > 0); });
assert.strictEqual(passed, 15);
console.log('Gutenberg event visuals block contract: 15/15 OK');
