const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const pluginRoot = path.resolve(root, '..', '..', '..', '..', '..');
const read = (...parts) => fs.readFileSync(path.join(...parts), 'utf8');
const metadata = JSON.parse(read(root, 'src', 'module.json'));
const source = read(root, 'src', 'index.jsx');
const php = read(pluginRoot, 'includes/integrations/divi/class-event-visuals-module.php');
const renderer = read(pluginRoot, 'includes/public/rendering.php');
const bootstrap = read(pluginRoot, 'includes/integrations/divi/bootstrap.php');
const publicScript = read(pluginRoot, 'includes/public/event-visuals-divi.js');
const publicStyles = read(pluginRoot, 'includes/public/event-visuals.css');
const plugin = read(pluginRoot, 'wp-seed-events.php');
const items = metadata.attributes.content.settings.innerContent.items;
const defaults = metadata.attributes.content.default.innerContent.desktop.value;
let passed = 0;
const test = (name, fn) => { fn(); passed += 1; console.log(`ok ${passed} - ${name}`); };

test('module identity and folder stay stable', () => { assert.strictEqual(metadata.name, 'wp-seed-events/event-visuals'); assert.strictEqual(metadata.folder, 'wp-seed-events'); });
test('module registers exactly once', () => assert.strictEqual((source.match(/registerModule\(metadata, eventVisualsModule\)/g) || []).length, 1));
test('content UI is image-only while legacy storage remains readable', () => { const text = JSON.stringify(metadata); assert.ok(Object.hasOwn(defaults, 'show_document')); assert.ok(!Object.values(items).some((item) => item.subName === 'show_document')); assert.ok(Object.hasOwn(metadata.attributes, 'documentStyle')); assert.ok(!metadata.attributes.documentStyle.settings); assert.ok(!text.includes('Document / Lien document')); });
test('click action replaces two toggles', () => { assert.strictEqual(items.clickAction.label, 'Action au clic'); assert.deepStrictEqual(Object.keys(items.clickAction.component.props.options), ['none', 'lightbox', 'original']); assert.ok(!items.linkOriginal); assert.ok(!items.lightbox); });
test('new module defaults to no click action', () => assert.strictEqual(defaults.click_action, 'none'));
test('new UI delegates collection layout to Divi', () => { ['layout', 'horizontalGap', 'verticalGap', 'alignItems', 'justifyContent', 'wrap', 'columns', 'columnsTablet', 'columnsPhone'].forEach((key) => assert.ok(!items[key])); assert.ok(!metadata.settings.groups.designVisualLayout); });
test('native Divi layout targets the real visuals list', () => { assert.ok(!metadata.attributes.module.settings.decoration?.layout); assert.ok(metadata.attributes.eventListStyle.settings.decoration.layout); assert.strictEqual(metadata.attributes.eventListStyle.selector, '{{selector}} .wp-seed-event-visuals__list'); });
test('legacy layout storage remains readable without becoming a new default', () => { ['layout', 'horizontal_gap', 'vertical_gap', 'align_items', 'justify_content', 'wrap', 'columns', 'columns_tablet', 'columns_phone'].forEach((key) => assert.ok(!Object.hasOwn(defaults, key))); assert.ok(php.includes("'layout'         => 'grid'")); });
test('new modules mark the native Divi layout contract', () => { assert.ok(source.includes("layout_contract: 'native-v1'")); assert.ok(php.includes("'native-v1' === $options['layout_contract']")); });
test('style surface has four business groups maximum', () => { const text = JSON.stringify(metadata); ['Module', 'Élément', 'Image', 'Légende'].forEach((label) => assert.ok(text.includes(label))); assert.ok(!text.includes('Disposition des visuels')); });
test('Divi native lightbox is used and initialized after preview mount', () => { assert.ok(php.includes("$processor->add_class( 'et_pb_lightbox_image' )")); assert.ok(php.includes("$options['click_action'] = 'original'")); assert.ok(source.includes('window.et_pb_image_lightbox_init')); assert.ok(source.includes("find('.et_pb_lightbox_image')")); });
test('frontend lightbox loads and calls only Divi native assets', () => {
  assert.ok(php.includes('DynamicAssetsUtils::enqueue_magnific_popup_script()'));
  assert.ok(php.includes("ET_BUILDER_URI . '/feature/dynamic-assets/assets/css/magnific_popup.css'"));
  assert.ok(php.includes("wp_enqueue_script( 'wp-seed-events-divi-visuals-lightbox' )"));
  assert.ok(publicScript.includes('window.et_pb_image_lightbox_init(links)'));
  assert.ok(!publicScript.includes('.magnificPopup({'));
  assert.ok(plugin.includes("array( 'jquery', 'magnific-popup' )"));
});
test('WordPress image source size is independent from native Divi display sizing', () => {
  assert.ok(renderer.includes('wp_get_attachment_image('));
  assert.ok(renderer.includes('$image_size'));
  assert.ok(metadata.attributes.itemStyle.settings.decoration.sizing);
  assert.ok(metadata.attributes.imageStyle.settings.decoration.sizing);
  assert.ok(publicStyles.includes('flex-basis: auto'));
  assert.ok(publicStyles.includes('inline-size: auto'));
  assert.ok(!publicStyles.includes('flex-basis: 100%'));
});
test('loop context uses canonical resolver', () => { assert.deepStrictEqual(metadata.usesContext, ['postId', 'queryId']); assert.ok(source.includes('resolveCurrentEventContext')); assert.ok(php.includes('wp_seed_events_divi_resolve_event_id')); assert.ok(!php.includes('get_the_ID()')); });
test('preview is protected and abortable', () => { assert.ok(php.includes('WP_REST_Server::READABLE')); assert.ok(php.includes('edit_posts')); assert.ok(source.includes('AbortController')); });
test('Event Data and shared renderer are single source', () => { assert.strictEqual((php.match(/wp_seed_events_get_event_data/g) || []).length, 1); assert.strictEqual((php.match(/wp_seed_events_render_public_event_visuals_section/g) || []).length, 1); assert.ok(!php.includes('get_post_meta')); });
test('public renderer contains no document branch', () => { const start = renderer.indexOf('function wp_seed_events_render_public_event_visuals_section'); const end = renderer.indexOf('function wp_seed_events_render_public_event_document_section'); assert.ok(!renderer.slice(start, end).includes('event_document')); });
test('build and bootstrap are wired', () => { assert.ok(fs.statSync(path.join(root, 'build/wp-seed-events-event-visuals.js')).size > 0); assert.ok(bootstrap.includes('wp_seed_events_divi_register_event_visuals_module')); });
assert.strictEqual(passed, 18);
console.log('Divi event visuals module contract: 18/18 OK');
