const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const pluginRoot = path.resolve(root, '..', '..', '..', '..', '..');
const metadata = JSON.parse(fs.readFileSync(path.join(root, 'src/module.json'), 'utf8'));
const source = fs.readFileSync(path.join(root, 'src/index.jsx'), 'utf8');
const php = fs.readFileSync(path.join(pluginRoot, 'includes/integrations/divi/class-event-document-module.php'), 'utf8');
const defaults = metadata.attributes.content.default.innerContent.desktop.value;
let passed = 0; const test = (name, fn) => { fn(); passed++; console.log(`OK ${passed} - ${name}`); };
test('module has a distinct stable ID', () => assert.strictEqual(metadata.name, 'wp-seed-events/event-document'));
test('module has exact content controls', () => assert.deepStrictEqual(Object.keys(defaults), ['show_document', 'link_text', 'name_display', 'name_position']));
test('new UI omits the redundant visibility toggle while runtime storage remains compatible', () => { assert.ok(!metadata.attributes.content.settings.innerContent.items.showDocument); assert.ok(php.includes("'show_document'")); });
test('default link text is exact', () => assert.strictEqual(defaults.link_text, 'Télécharger le document'));
test('link text follows the native Divi object-attribute text contract', () => {
  const item = metadata.attributes.linkText.settings.innerContent.item;
  assert.strictEqual(metadata.attributes.linkText.type, 'object');
  assert.strictEqual(item.attrName, 'linkText.innerContent');
  assert.strictEqual(item.component.name, 'divi/text');
  assert.strictEqual(item.component.type, 'field');
  assert.strictEqual(metadata.attributes.linkText.default.innerContent.desktop.value, defaults.link_text);
  assert.ok(!metadata.attributes.content.settings.innerContent.items.linkText);
});
test('name modes are exact', () => assert.deepStrictEqual(Object.keys(metadata.attributes.content.settings.innerContent.items.nameDisplay.component.props.options), ['text', 'name', 'text_name']));
test('name positions are exact', () => assert.deepStrictEqual(Object.keys(metadata.attributes.content.settings.innerContent.items.namePosition.component.props.options), ['inline', 'next_line']));
test('style surface is simple', () => { const text = JSON.stringify(metadata); ['Module', 'Document / Lien', 'Nom du document'].forEach((label) => assert.ok(text.includes(label))); });
test('uses Event Data and shared renderer only', () => { assert.strictEqual((php.match(/wp_seed_events_get_event_data/g) || []).length, 1); assert.strictEqual((php.match(/wp_seed_events_render_public_event_document_section/g) || []).length, 1); assert.ok(!php.includes('get_post_meta')); });
test('loop preview uses canonical context', () => { assert.ok(source.includes('resolveCurrentEventContext')); assert.ok(source.includes('loopIndex')); assert.ok(source.includes('parentId')); });
test('preview consumes the live attrs supplied by the Divi edit renderer', () => { assert.ok(source.includes('options(attrs)')); assert.ok(!source.includes('runtimeModuleAttrs')); assert.ok(!source.includes('effectiveAttrs')); });
test('new link text wins while the historical nested value remains readable', () => { assert.ok(source.includes('linkTextValue(attrs)')); assert.ok(source.includes('value.link_text')); assert.ok(php.includes('get_link_text_value')); assert.ok(php.includes("$attrs['linkText']['innerContent']['desktop']['value']")); });
test('preview is read-only protected and abortable', () => { assert.ok(php.includes('WP_REST_Server::READABLE')); assert.ok(php.includes('edit_posts')); assert.ok(source.includes('AbortController')); });
test('bundle exists', () => assert.ok(fs.statSync(path.join(root, 'build/wp-seed-events-event-document.js')).size > 0));
assert.strictEqual(passed, 14); console.log('Divi event document module contract: 14/14 OK');
