const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const pluginRoot = path.resolve(root, '..', '..', '..', '..');
const metadata = JSON.parse(fs.readFileSync(path.join(root, 'src/block.json'), 'utf8'));
const built = JSON.parse(fs.readFileSync(path.join(root, 'build/block.json'), 'utf8'));
const source = fs.readFileSync(path.join(root, 'src/index.js'), 'utf8');
const php = fs.readFileSync(path.join(pluginRoot, 'includes/integrations/gutenberg/event-document-block.php'), 'utf8');
let passed = 0; const test = (name, fn) => { fn(); passed++; console.log(`OK ${passed} - ${name}`); };
test('block has distinct stable ID', () => assert.strictEqual(metadata.name, 'wp-seed-events/event-document-block'));
test('built metadata matches source', () => assert.deepStrictEqual(built, metadata));
test('attributes are exact', () => assert.deepStrictEqual(Object.keys(metadata.attributes), ['show_document', 'link_text', 'name_display', 'name_position']));
test('name modes and positions are exact', () => { assert.deepStrictEqual(metadata.attributes.name_display.enum, ['text', 'name', 'text_name']); assert.deepStrictEqual(metadata.attributes.name_position.enum, ['inline', 'next_line']); });
test('dynamic block has no persisted event ID', () => { assert.ok(source.includes('save: () => null')); assert.ok(!Object.hasOwn(metadata.attributes, 'eventId')); });
test('uses shared Event Data renderer', () => { assert.ok(php.includes('wp_seed_events_get_event_data')); assert.ok(php.includes('wp_seed_events_render_public_event_document_section')); assert.ok(!php.includes('get_post_meta')); });
test('preview is protected', () => assert.ok(php.includes('wp_seed_events_gutenberg_event_visuals_preview_permissions')));
test('bundle exists', () => assert.ok(fs.statSync(path.join(root, 'build/index.js')).size > 0));
assert.strictEqual(passed, 8); console.log('Gutenberg event document block contract: 8/8 OK');
